### ISSUE TITLE
Want to help

### ISSUE THREAD

**Issue by umaranis** [exercism/fsharp-test-runner#1]
Hi,

I am a mentor for F# track and want to help building the test runner.

**Comment by ErikSchierboom** [comment]
Great to hear! I'll let you know when we have something to work with (the test runner format is still being worked on).

**Comment by ErikSchierboom** [comment]
@umaranis I've just merged the first version of the C# test runner, which you should be able to tweak a little and then have it work for F#: https://github.com/exercism/csharp-test-runner

**Comment by umaranis** [comment]
Cool @ErikSchierboom. I will give it go.

**Comment by umaranis** [comment]
@ErikSchierboom I have tweaked the code to work for F#.

How can I commit the code? Don't have access on the repo and can't fork it because no code there yet?

**Comment by iHiD** [comment]
@umaranis I've created a README, so you can now fork and PR :)

**Comment by iHiD** [comment]
(Erik is on holiday this week so won't be as responsive as normal)

**Comment by ErikSchierboom** [comment]
Indeed I am! With the help of @ihid, are you now able to submit a PR @umaranis?

**Comment by umaranis** [comment]
PR submitted :)

**Comment by ErikSchierboom** [comment]
Closed by #2 .
