### ISSUE TITLE
Test runner failing for big test files

### ISSUE THREAD

**Issue by umaranis** [exercism/fsharp-test-runner#3]
Test runner fails with the following error if the test file is big in size.

```
{
  "status": "error",
  "message": "BeerSongTest.fs(99,1): error FS0010: Incomplete structured construct at or before this point in expression. Expected ']' or other token. \nBeerSongTest.fs(71,9): error FS0598: Unmatched '[' \nBeerSongTest.fs(70,5): error FS0588: The block following this 'let' is unfinished. Every code block is an expression and must have a result. 'let' cannot be the final code element in a block. Consider giving this block an explicit result. \nBeerSongTest.fs(98,11): error FS0514: End of file in string begun at or before here",
  "tests": []
}
```

To produce, try running it for `beer-song` exercise.

**Comment by umaranis** [comment]
The root cause of the problem:

In `run.ps1`, `Enable-All-Tests` function is producing a truncated test file. It seems that there is a limit of the number of characters pipe operator can handle.

```
function Enable-All-Tests {
    Get-Content $testFile | Unskip-All-Tests | Set-Content $testFile
}
```

Changing the code slightly avoid the second pipe operator, resolves the issue.
```
function Enable-All-Tests {
    $content = Get-Content $testFile | Unskip-All-Tests
    $content | Set-Content $testFile
}
```

**Comment by umaranis** [comment]
Hi @ErikSchierboom, could you reproduce it at your end?

**Comment by ErikSchierboom** [comment]
@umaranis Yep, I can confirm the same happens on my machine. Your fix looks good. Would you be willing to open a PR to fix this? If so, you could perhaps also send a similar PR to the [C# test runner repository](https://github.com/exercism/csharp-test-runner).

Note: are there more locations where we use the pipe operator and that could truncate the text?
