### ISSUE TITLE
Allow running tests that are defined in a class

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp-test-runner#32]
Most tests are defined as standalone functions. Some are defined in a class though (e.g. for cleanup purposes). This currently breaks the test runner, as the code to capture console output creates a class for the existing code. We should detect if a class is used in the tests and update the rewriting code accordingly.

**Comment by polforsrc** [comment]
Same thing happened to me.  The function "createFiles()" is defined in the file "GrepTests.fs" and it works fine locally but doesn't work in the online tests.

> GrepTests.fs(15,9): error FS0039: The value or constructor 'createFiles' is not defined.
