### ISSUE TITLE
Unskip all types of tests

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/fsharp-test-runner#33]
Ensures that all `Skip` properties are removed, regardless of the type of attribute. Without this, the `diamond` exercise's tests won't be unskipped (they use property-based testing).

See https://github.com/exercism/csharp-test-runner/pull/67 for the C# equivalent PR.

**Comment by martinfreedman** [comment]
I will look into this as we are following in the [PR1029](https://github.com/exercism/fsharp/pull/1029).
