### ISSUE TITLE
'Diamond' test run fails without error message

### ISSUE THREAD

**Issue by ThorstenReichert** [exercism/fsharp-test-runner#36]
For the [Diamond](https://exercism.org/tracks/fsharp/exercises/diamond) exercise in F#, the submission below fails with an empty error message, stating only "We received the following error when we ran your code", but no actual reason.

![image](https://user-images.githubusercontent.com/15281083/140563189-638f8510-7355-45df-bab2-c7880ac36ea3.png)

Looking at the dev console in my browser, I see multiple calls to the "test_run_ endpoint returning
```json
{"test_run":null}
```
with status 304. If I modify my submission slightly by defining
```fsharp
let space = '.' // instead of let space = ' '
```
then I receive a "test_run" response with status 200 and some expected test failure messages (after some empty 304s as above).

The code submission:
```fsharp
module Diamond

let alphabet = [|'A'..'Z'|]
let space = ' '

let createUpperHalfRow row size =
    let center = size / 2
    if row = 0 then
        Array.init size (fun i -> if i = center then alphabet.[row] else space)
    else
        Array.init size (fun i -> if i = center - row || i = center + row then alphabet.[row] else space)


let createUpperHalf size =
    Array.init (size / 2 + 1) (fun i -> createUpperHalfRow i size)

let mirrorLowerHalf upperHalf =
    let length = Array.length upperHalf
    Array.init (length - 1) (fun i -> upperHalf.[length - i - 2])

let make letter = 
    let size = (Array.findIndex ((=) letter) alphabet) * 2 + 1
    let upperHalf = createUpperHalf size
    let lowerHalf = mirrorLowerHalf upperHalf

    lowerHalf
    |> Array.append upperHalf
    |> Array.map System.String
    |> String.concat System.Environment.NewLine
```

**Comment by ErikSchierboom** [comment]
See https://github.com/exercism/fsharp/issues/1022

**Comment by ErikSchierboom** [comment]
@ThorstenReichert We've just deployed a fix. Could you verify that re-running the tests now works for you?
