### ISSUE TITLE
'Grep` test run fails without error message

### ISSUE THREAD

**Issue by martinfreedman** [exercism/fsharp-test-runner#48]
Similar to Daimond but this does not use property testing. It  is using the test as members of a type which is unusual. Could the rewrite affect that?

Checked with a student whose tests pass locally and then  with my  existing submitted solution.

**Comment by ErikSchierboom** [comment]
Yes, see https://github.com/exercism/fsharp-test-runner/issues/32

**Comment by martinfreedman** [comment]
Checked today. Still timing out

**Comment by ErikSchierboom** [comment]
@martinfreedman As mentioned above, this is caused by #32, which isn't yet fixed.

**Comment by martinfreedman** [comment]
Ah sorry. I thought it was already merged.

**Comment by ErikSchierboom** [comment]
Yeah, it's been tough. I'm considering dropping the printf debugging support altogether from the F# test runner, as it is a huge PITA.

**Comment by martinfreedman** [comment]
That is a pity its a PITA ;-) It is a very useful feature for the online editor

**Comment by ErikSchierboom** [comment]
I know :( We might later on try to re-enable it again, but that may involve choosing a different testing framework.
